[theme]
base = "dark"
primaryColor = "#4d7cfe"
backgroundColor = "#04060e"
secondaryBackgroundColor = "#0c1424"
textColor = "#d7e3f0"
font = "sans serif"

[server]
headless = true
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false
