[theme]
base = "dark"
primaryColor = "#5686fe"
backgroundColor = "#151517"
secondaryBackgroundColor = "#232324"
textColor = "#cfd3d6"
font = "sans serif"

[server]
headless = true
runOnSave = true
fileWatcherType = "poll"

[browser]
gatherUsageStats = false
